var i=2;
function addTeach() {
    i++;
    var str = "";
    str += "<li class=\"teach_li\">"
    str += "<ol class=\"teach_ol\">"
    str += "<li class=\"ol_li clearfix\">"
    str += "<span class=\"name fl\">园长姓名："
    str += "</span>"
    str += "<input type=\"name\" name=\"student_name\" placeholder=\"\" value=\"\" class=\"required fl\">"
    str += "</li>"
    str += "<li class=\"ol_li clearfix\">"
    str += "<span class=\"name fl\">园长性别："
    str += "</span>"
    str += "<div class=\"con fl\">"
    str += "<div class=\"radio checkbox_label\">"
    str += "<input class=\"magic-checkbox\" type=\"checkbox\" name=\"sex\" id=\"1\">"
    str += "<label for=\"1\" class=\"chevkbox_list\">男"
    str += "</label>"
    str += "</div>"
    str += "<div class=\"radio checkbox_label\">"
    str += "<input class=\"magic-checkbox\" type=\"checkbox\" name=\"sex\" id=\"2\">"
    str += "<label for=\"2\" class=\"chevkbox_list\">女"
    str += "</label>"
    str += "</div>"
    str += "</div>"
    str += "</li>"
    str += "<li class=\"ol_li clearfix\">"
    str += "<span class=\"name fl\">园长学历："
    str += "</span>"
    str += "<span class=\"con_sele\">"
    str += "<select name=\"type_id\" id=\"type_id\" data-role=\"none\" data-value=\"关系\" class=\"form_select\">"
    str += "<option value=\"0\">博士</option>"
    str += "<option value=\"1\">硕士</option>"
    str += "<option value=\"2\">本科</option>"
    str += "<option value=\"3\">专科</option>"
    str += "<option value=\"4\">其他</option>"
    str += "</select>"
    str += "<span class=\"arr_icon\">"
    str += "</span>"
    str += "</span>"
    str += "</li>"
    str += "</ol>"
    str += "<div class=\"teach_mess\">"
    str += "<h3 class=\"teach_title\">园长简介</h3>"
    str += " <div class=\"envi_teach\">"
    str += "<textarea class=\"exam_text\" onkeyup=\"fn1(this)\" onPaste=\"fn1(this)\" oninput=\"fn1(this)\"  onfocus=\"$(this).autoHeight();\" maxlength=\"200\" placeholder=\"示例：让孩子在快乐中体验、学习、成长！多元探索，创造性学习等\">"
    str += "</textarea>"
    str += " <div class=\"clearfix examples\">"
    str += "<p class=\"length fr\">（可输入"
    str += "<span>0</span>"
    str += "/200字）</p>"
    str += "</div>"
    str += " </div>"
    str += "<div class=\"container\">"
    str += "<div class=\"z_photo  clearfix\">"
    str += "<div class=\"z_file p_flie"+(i)+"\">"
    str += "<input type=\"file\" name=\"file\" id=\"file"+(i)+"\" value=\"\" accept=\"image/*\" multiple=\"\" onchange=\"imgChange('photo_flie"+(i)+"','p_flie"+(i)+"','file"+(i)+"');\">"
    str += "</div>"
    str += "<div class=\"z_photo_div photo_flie"+(i)+" clearfix\">"
    str += "</div>"
    str += "</div>"
    str += "</div>"
    str += "<p class=\"prompt_img\">可添加园长形象照，最多9张</p>"
    str += "</div>"
    str += "</li>"
    return str;
}